apiVersion: v1
kind: Pod
metadata:
  name: dal
  labels:
    name: dal
spec:
  containers:
  - name: dal
    image: itielshwartz/microservice-using-helm:part-4-dal
    ports:
    - containerPort: 5000
