apiVersion: v1
kind: Pod
metadata:
  name: main
spec:
  containers:
  - name: main
    image: itielshwartz/microservice-using-helm:part-5-backend
    ports:
    - containerPort: 8080
    env:
    - name: DAL_URL
      value: "http://quotes-dal:5000"